name: Mi Flujo de Trabajo

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga un push a la rama main

jobs:
  mi_trabajo:
    runs-on: ubuntu-latest

    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'

      # You can replace this next step with any JUnit XML parser of your choosing
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true
